/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Shopping;

//import static Shopping.ShoppingList.lines;
import static Shopping.ShoppingList.lm1;
import java.awt.List;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
//import static Shopping.ShoppingList.prodList;
import java.io.PrintWriter;
import static java.nio.file.Files.lines;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import static javax.management.Query.lt;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author Kamil
 */
public class ManageProducts extends javax.swing.JFrame {

    DefaultListModel lm1MP = new DefaultListModel();
    //ShoppingList shopping = new ShoppingList();
    public boolean result;
    DefaultComboBoxModel cb = new DefaultComboBoxModel();

    /**
     * Creates new form ManageProducts
     */
    public ManageProducts() {
        initComponents();
        connectList();
        cb.setSelectedItem("None");
        //jList2.setModel(ShoppingList.lm1);
//        String line;
//        try {
//            BufferedReader in = new BufferedReader(new FileReader("C:\\share\\ProductsList.txt"));
//
//            while ((line = in.readLine()) != null) {
//                String[] lines = line.split(",");
//                Arrays.sort(lines);
//                for (String ls : lines) {
//
//                    lm1MP.addElement(ls);
//
//                }
//
//            }
//
//            jList2.setModel(lm1MP);
//            in.close();
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
    }

    public void connectList() {
        try {
            DBConnection dbcon = new DBConnection();

            String sql = "SELECT * FROM products";
            Statement ps = dbcon.connect().createStatement();
//                if(ps.isClosed()==true){
//                    System.out.print("pSSSSSS");
//                }
            ResultSet rs = ps.executeQuery(sql);
            while (rs.next()) {

                String productName = rs.getString("product_name");
                //System.out.println(productName);
                lm1MP.addElement(productName);
            }
            String sql1 = "SELECT product_group_name FROM product_groups";
            ps = dbcon.connect().createStatement();
//                if(ps.isClosed()==true){
//                    System.out.print("pSSSSSS");
//                }
            rs = ps.executeQuery(sql1);
            while (rs.next()) {

                String productName = rs.getString("product_group_name");
                //System.out.println(productName);
                cb.addElement(productName);
            }
            rs.close();
            ps.close();
            jComboBox1.setModel(cb);
            jList2.setModel(lm1MP);

        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane2.setViewportView(jList2);

        jLabel1.setText("Products list");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Product name");

        jLabel3.setText("Group name");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(38, 38, 38))
                                    .addComponent(jComboBox1, 0, 111, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean d = duplicatedProduct();
        String s = jTextField1.getText();
        String pGroups = (String) jComboBox1.getSelectedItem();
        char[] c = s.toCharArray();
        if (!(s.equals(""))) {
            if ((Character.isUpperCase(c[0]))) {
                if (pGroups != "None") {

                    try {
                      DBConnection dbcon = new DBConnection();

                        String sql = "insert into products (product_name, product_group_id) values ('" + s + "', (select product_group_id from product_groups where product_group_name='" + pGroups + "'));";
                        executeSQLQuery(sql);
                        lm1MP.removeAllElements();
                        String sql1 = "SELECT * FROM products";
                        Statement ps = dbcon.connect().createStatement();
//                if(ps.isClosed()==true){
//                    System.out.print("pSSSSSS");
//                }
                        ResultSet rs = ps.executeQuery(sql1);
                        while (rs.next()) {

                            String productName = rs.getString("product_name");
                            //System.out.println(productName);
                            lm1MP.addElement(productName);
                        }
                        rs.close();
                        ps.close();
                        //jComboBox1.setModel(cb);
                        jList2.setModel(lm1MP);
                    } catch (SQLException ex) {
                        new ProductEntryError(this, rootPaneCheckingEnabled).setVisible(true);
                    }

//                lm1MP.addElement(jTextField1.getText());
//                jList2.setModel(lm1MP);
                    //jList2.setModel(lm1);
                    jTextField1.setText("");

                } else {
                    new ProductEntryError(this, rootPaneCheckingEnabled).setVisible(true);

                }
            } else {
                new ProductEntryError(this, rootPaneCheckingEnabled).setVisible(true);

            }

        } else {
            new ProductEntryError(this, rootPaneCheckingEnabled).setVisible(true);
           
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean duplicatedProduct() {
        ListModel newProdList = jList2.getModel();
        String sNewProdList = newProdList.toString();
        sNewProdList = sNewProdList.substring((sNewProdList.indexOf("[")) + 1, sNewProdList.indexOf("]"));
        String[] products = sNewProdList.split(",");
        String getProductName = jTextField1.getText();

        for (String product : products) {
            product = product.substring(product.indexOf(" ") + 1);
            if (product.equals(getProductName)) {

                result = true;
                break;
            } else {
                result = false;
            }
        }
        return result;
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        BufferedWriter out = null;
//        try {
//
//            out = new BufferedWriter(new FileWriter("C:\\share\\ProductsList.txt"));
//            ListModel newProdList = jList2.getModel();
//            String sNewProdList = newProdList.toString();
//            sNewProdList = sNewProdList.substring((sNewProdList.indexOf('[')) + 1, sNewProdList.indexOf(']'));
//
//            // sNewProdList = sNewProdList.replaceAll("[", "");
//            // sNewProdList = sNewProdList.replaceAll("]", "");
//            // sNewProdList = sNewProdList.substring((sNewProdList.indexOf(', ')) + 1)
//            String[] products = sNewProdList.split(", ");
//            Arrays.sort(products);
//            for (String product : products) {
//                out.write(product + "\n");
//            }
//
//            out.close();
//
//            lm1.removeAllElements();
//            String line;
//            BufferedReader in = new BufferedReader(new FileReader("C:\\share\\ProductsList.txt"));
//
//            while ((line = in.readLine()) != null) {
//                String[] lines = line.split(",");
//                Arrays.sort(lines);
//                for (String ls : lines) {
//
//                    lm1.addElement(ls);
//
//                }
//
//            }
//
//            jList2.setModel(lm1);
//            in.close();
        setVisible(false);
        dispose();
        ShoppingList.lm1.removeAllElements();
        try {
            DBConnection dbcon = new DBConnection();

            String sql = "SELECT * FROM products LIMIT 100";
            Statement ps = dbcon.connect().createStatement();
//                if(ps.isClosed()==true){
//                    System.out.print("pSSSSSS");
//                }
            ResultSet rs = ps.executeQuery(sql);
            while (rs.next()) {

                String productName = rs.getString("product_name");
                //System.out.println(productName);
                ShoppingList.lm1.addElement(productName);
            }
            rs.close();
            ps.close();
            jList2.setModel(lm1);

        } catch (Exception e) {

        }
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setVisible(false);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //String s =  jList2.getSelectedValue();
    String sql1 = "delete from products where product_name='" + jList2.getSelectedValue() + "'";
        //Statement ps = dbcon.connect().createStatement();
//                if(ps.isClosed()==true){
//                    System.out.print("pSSSSSS");
//                }
        // ResultSet rs = ps.executeQuery(sql1);
        //  lm1MP.removeAllElements(s);

        // jList2.setModel(lm1MP);
        executeSQLQuery(sql1);
        lm1MP.removeAllElements();
        try {
            DBConnection dbcon = new DBConnection();

            String sql = "SELECT * FROM products LIMIT 100";
            Statement ps = dbcon.connect().createStatement();
//                if(ps.isClosed()==true){
//                    System.out.print("pSSSSSS");
//                }
            ResultSet rs = ps.executeQuery(sql);
            while (rs.next()) {

                String productName = rs.getString("product_name");
                //System.out.println(productName);
                lm1MP.addElement(productName);
            }
            rs.close();
            ps.close();
            jList2.setModel(lm1MP);

        } catch (Exception e) {

        }

//        int indexL1 = jList2.getSelectedIndex();
//        lm1MP.remove(indexL1);
//        jList2.setModel(lm1MP);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void executeSQLQuery(String query) {
        DBConnection dbcon = new DBConnection();
        Statement st;
        try {
            st = dbcon.connect().createStatement();
            st.executeUpdate(query);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProducts().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
